source :rubygems

# Project requirements
gem 'rake'
gem 'rack-flash'
gem 'thin' # or mongrel

# Component requirements
gem 'bcrypt-ruby', :require => "bcrypt"
gem 'haml'
gem 'activerecord', :require => "active_record"
gem 'sqlite3-ruby', :require => "sqlite3"

# Test requirements
gem 'shoulda', :group => "test"
gem 'rack-test', :group => "test", :require => "rack/test"


# Padrino
gem 'padrino', "0.9.20"
